name: fast_shopping
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.12.0
  http: ^0.13.6
  google_fonts: ^4.0.4
  freezed: ^2.3.4
  bloc: ^8.1.1
  firebase_auth: ^4.6.0
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  go_router: ^7.0.1
  injectable: ^2.1.1
  flutter_bloc: ^8.1.2
  google_sign_in: ^6.1.0
  get_it: ^7.6.0
  provider: ^6.0.5
  cloud_firestore: ^4.7.1
  dart_jsonwebtoken: ^2.7.1
  qr_code_scanner: ^1.0.1
  image_gallery_saver: ^2.0.1
  permission_handler: ^10.3.0

  material_flat_bottom_bar:
    git:
      url: https://github.com/yako-dev/flutter-material-flat-bottom-bar.git
      ref: migration-to-null-safety
  mocktail: ^0.3.0
  qr_flutter: ^4.0.0
  path_provider: ^2.0.15
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  bloc_test: ^9.1.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
