name: fast_shopping
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.12.0
  http: ^0.13.6
  google_fonts: ^4.0.4
  freezed: ^2.3.4
  bloc: ^8.1.1
  firebase_auth: ^4.6.0
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  go_router: ^7.0.1
  injectable: ^2.1.1
  flutter_bloc: ^8.1.2
  google_sign_in: ^6.1.0
  get_it: ^7.6.0
  provider: ^6.0.5
  cloud_firestore: ^4.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
